// <auto-generated />
namespace SG_ASP_3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class renamedb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renamedb));
        
        string IMigrationMetadata.Id
        {
            get { return "202105151619184_renamedb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
