// <auto-generated />
namespace SG_ASP_3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_espeMedic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_espeMedic));
        
        string IMigrationMetadata.Id
        {
            get { return "202106151657475_add_espeMedic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
